#!.venv/bin/python
"Update external IP v4 and/or v6 addresses to dynamic DNS servers."
# Mark Blakeney, Nov 2016.

from __future__ import annotations

import argparse
import asyncio
import json
import re
import sys
import time
from collections import deque
from hashlib import sha256 as hasher
from ipaddress import IPv4Address, IPv6Address
from pathlib import Path
from typing import Any, ClassVar, final

import ifaddr
import platformdirs
from aiohttp import ClientSession as Session

if sys.version_info >= (3, 11):
    import tomllib
else:
    import tomli as tomllib  # type: ignore

import convtime

PROG = Path(__file__).stem
CACHEDIR = platformdirs.user_cache_path() / PROG
CONFFILE = platformdirs.user_config_path() / f'{PROG}.toml'
IPCACHE = CACHEDIR / 'ipaddrs'
URLCACHE = CACHEDIR / 'urls'

ADDRESS_TYPES = {'ipv4': IPv4Address, 'ipv6': IPv6Address}
ADDRESS_TXT = ' or '.join(ADDRESS_TYPES)
OFFSTATES = {'off', 'no', 'none', 'false'}

# Process command line options
opt = argparse.ArgumentParser(description=__doc__)
opt.add_argument('-v', '--verbose', action='store_true', help='verbose output')
opt.add_argument(
    '-i', '--ignore-cache', action='store_true', help='ignore cache for startup'
)
opt.add_argument(
    '-c',
    '--conf',
    default=str(CONFFILE),
    help=f'configuration file, default = {CONFFILE}',
)
args = opt.parse_args()

conffile = Path(args.conf)
if not conffile.exists():
    sys.exit(f'ERROR: Configuration file "{conffile}" does not exist.')

# Get configuration values
with conffile.open('rb') as fp:
    conf = tomllib.load(fp)

tconf = conf.get('times', {})
poll_period = int(convtime.tosec(tconf.get('poll_period', '10m')))
force_period = int(convtime.tosec(tconf.get('force_period', '24h'))) * 1000_000_000


def log(msg: str) -> None:
    "Log message to stdout"
    print(msg, flush=True)


def logerr(msg: str) -> None:
    "Log message to stderr"
    print(msg, file=sys.stderr, flush=True)


async def urlget(
    session: Session, url: str, headers: dict[str, str] | None = None
) -> str | None:
    "Fetch given url"
    try:
        async with session.get(url, headers=headers) as response:
            response.raise_for_status()
            txt = await response.text()
    except Exception as e:
        logerr(str(e))
        return None

    return txt.strip() if txt else ''


@final
class IPPROVIDER:
    types: ClassVar[set[str]] = set()

    def __init__(
        self, name: str, interface_name: str | None, servers: list[str]
    ) -> None:
        "Create IP provider type to fetch a v4 or v6 IP address"
        address_type = ADDRESS_TYPES.get(name)
        if not address_type:
            sys.exit(f'ERROR: Invalid IP type {name} configured.')
        self.address_type = address_type

        if not interface_name and len(servers) < 1:
            sys.exit(
                f'ERROR: Must define at least 1 {name} ip source (interface name or server).'
            )

        self.name = name
        self.interface_name = interface_name
        self.servers = deque(servers)
        self.types.add(name)
        self.file = IPCACHE / name
        self.session = None
        self.ip: str | None = None
        self.failed = False

        # Load fetch values from last time we ran
        if self.file.exists() and not args.ignore_cache:
            try:
                self.ip = self.file.read_text()
            except Exception:
                self.file.unlink()

        log(
            f'Configured ip provider {name}: interface={self.interface_name}, servers={",".join(self.servers)}'
        )

    def ip_valid(self, ipstr: str | None) -> str | None:
        "Return formatted ip string if passed IP address valid and global"
        if not ipstr or not self.address_type:
            return None

        try:
            ip = self.address_type(ipstr)
            if not ip.is_global:
                return None
            return ip.exploded
        except Exception:
            return None

    def _persist_ip(self, ip: str, source: str, verbose: bool):
        if verbose or self.failed:
            log(f'Fetched {self.name} address {ip} from {source}')

        if ip and ip != self.ip:
            log(f'{self.name} address changed from {self.ip} to {ip} ({source})')
            self.ip = ip
            _ = self.file.write_text(ip)

        self.failed = False

    async def get_ip(self) -> IPPROVIDER | None:
        "Return IPPROVIDER if IP address was fetched successfully"
        # Set session handle 1st time (must be done in async func)
        if not self.session:
            self.session = Session()
            first = True
        else:
            first = False

        # first attempt to read IP from interface, if configured
        if self.interface_name:
            try:
                # a single interface might have multiple IP addresses
                # only accept if there is only a single global one
                ip_strings = (
                    i.ip[0] if isinstance(i.ip, tuple) else i.ip
                    for i in next(
                        a.ips
                        for a in ifaddr.get_adapters()
                        if a.name == self.interface_name
                    )
                )
                ips = [
                    valid_ip
                    for ip in ip_strings
                    if (valid_ip := self.ip_valid(ip)) is not None
                ]
            except Exception:
                ips = []

            if len(ips) != 1:
                if not self.failed:
                    logerr(
                        f"Couldn't fetch {self.name} address on local interface ({self.interface_name} with {len(ips)} global addresses)"
                    )
            else:
                self._persist_ip(
                    ips[0], f'interface {self.interface_name}', args.verbose or first
                )
                return self

        # then attempt to poll server
        for index, url in enumerate(self.servers):
            ip = await urlget(self.session, url)
            ip_valid = self.ip_valid(ip)
            if not ip_valid:
                if not self.failed:
                    logerr(f'Failed to fetch {self.name} address from {url} (#{index})')
            else:
                # Rotate server list so that last good is first
                self.servers.rotate(-index)

                self._persist_ip(ip_valid, f'{url} (#{index})', args.verbose or first)
                return self

        if not self.failed:
            logerr(f'Failed to obtain {self.name} address from any source')
            self.failed = True

        return None


@final
class URL:
    allneeds: ClassVar[set[str]] = set()

    def __init__(self, conf: dict[str, Any]) -> None:
        "Create URL for sending to dyndns server"
        self.url = conf.get('url')
        if not self.url:
            sys.exit('ERROR: url not defined')

        headers = conf.get('headers')
        if isinstance(headers, dict):
            self.request_headers: dict[str, str] = headers
        elif headers is not None:
            sys.exit(f'ERROR: url {self.url}, headers must be a dictionary.')
        else:
            self.request_headers = {}

        # Record which IP address types we need for this URL
        self.needs = {k for k in ADDRESS_TYPES if self.url and f'<{k}>' in self.url}

        if (auto := conf.get('auto', 'off').lower()) not in OFFSTATES:
            if auto not in ADDRESS_TYPES:
                sys.exit(f'ERROR: url {self.url}, auto={auto} not valid.')

            self.needs.add(auto)

        if not self.needs:
            sys.exit(f'ERROR: url {self.url} must specify either {ADDRESS_TXT}')

        # Sanity check configuration
        for key in self.needs:
            if key not in IPPROVIDER.types:
                sys.exit(
                    f'ERROR: URL {self.url} needs {key} but {key} server '
                    + 'is not configured.'
                )

        response = conf.get('response')

        response_l: list[str] = []
        if isinstance(response, str):
            response_l.append(response)
        elif isinstance(response, list):
            response_l.extend(response)
        elif response is not None:
            sys.exit(f'ERROR: url {self.url}, response must be string or list.')

        self.response: list[re.Pattern[str]] = [re.compile(s) for s in response_l]
        URL.allneeds |= self.needs
        self.file = URLCACHE / hasher(self.url.encode()).hexdigest()
        self.session = None
        self.time = None
        self.failed: set[str] = set()
        self.values = {}

        # Add url to cache save data merely for ID/comment
        self.cache_data = {'url': self.url}

        # Load sent values from last time we ran
        if self.file.exists() and not args.ignore_cache:
            try:
                with self.file.open() as fp:
                    self.values = json.load(fp)
            except Exception:
                self.file.unlink()
            else:
                self.time = self.file.stat().st_mtime_ns + force_period
                # Remove url (comment) field
                if 'url' in self.values:
                    del self.values['url']

        needs = ' and '.join(self.needs)
        log(f'Configured URL {self.url}: {needs}')

    async def set_ips(self, now: int, values: dict[str, str]) -> None:
        "Send IP addresses to this dyndns server"
        failed = self.needs - set(values)

        # Strip out only the values we need for this URL and use
        # previous values for those that are failed
        values = {k: values.get(k, self.values.get(k, '?')) for k in self.needs}

        if failed != self.failed:
            if failed:
                missing = ' and '.join(failed)
                log(f'url {self.url} missing {missing} data')
            else:
                recovered = ' and '.join(self.failed)
                log(f'url {self.url} recovered {recovered} data')

            self.failed = failed

        # Only send on change or if "force_period" is due
        change = values != self.values
        if not change and self.time and now < self.time:
            return

        # Substitute IPs into URL
        if not (url := self.url):
            return

        for key, value in values.items():
            url = url.replace(f'<{key}>', value)

        # Set session handle 1st time (must be done in async func)
        if not self.session:
            self.session = Session()

        # Send to dyndns server
        response = await urlget(self.session, url, self.request_headers)
        if response is not None:
            if not self.response or any(s.search(response) for s in self.response):
                # Update successful, save new record to cache file
                self.cache_data.update(values)
                with self.file.open('w') as fp:
                    json.dump(self.cache_data, fp)

                self.values = values
                self.time = now + force_period
                if args.verbose or change:
                    if response:
                        response = f': {response}'
                    types = ' & '.join(self.needs)
                    log(f'Sent {url} for {types}{response}')
            else:
                logerr(f'URL {url} responded with error: {response}')
        else:
            logerr(f'Failed to send {url}')


async def main() -> None:
    "Main code"
    IPCACHE.mkdir(parents=True, exist_ok=True)
    URLCACHE.mkdir(parents=True, exist_ok=True)

    # Build list of IP address providers
    all_providers: dict[str, IPPROVIDER] = {}
    for k, c in conf.get('provider', {}).items():
        all_providers[k] = IPPROVIDER(k, c.get('interface'), c.get('servers', list()))

    if len(all_providers) < 1:
        sys.exit(f'ERROR: Must define at least one {ADDRESS_TXT} address provider.')

    # Build list of dyndns urls
    urls = [URL(c) for c in conf.get('urls', {})]

    if len(urls) < 1:
        sys.exit('ERROR: Must define at least one url.')

    # Now discard IP address types we dont actually need after reading URLs
    providers = [all_providers[k] for k in URL.allneeds]

    while True:
        # Get IP addresses in parallel
        ips = await asyncio.gather(*(p.get_ip() for p in providers))
        ips_vals = {s.name: s.ip for s in ips if s and s.ip}
        now = time.time_ns()

        # Got all addresses, now send to dyndns URLs in parallel
        _ = await asyncio.gather(*(u.set_ips(now, ips_vals) for u in urls))
        await asyncio.sleep(poll_period)


asyncio.run(main())
